/* Sweat & Stats v2.4.0.2.2 Completion & Compliance Patch */
(() => {
'use strict';
const VERSION='2.4.0.2.2', SCHEMA=2422;
const el=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const cp=v=>JSON.parse(JSON.stringify(v));
const special={'trx':'TRX','trx / suspension':'TRX / Suspension','ez curl bar':'EZ Curl Bar','bodyweight':'Bodyweight','dumbbell':'Dumbbell','barbell':'Barbell','kettlebell':'Kettlebell','cardio machine':'Cardio Machine'};
const normalize=s=>{const t=String(s||'').trim().replace(/\s+/g,' ');return special[t.toLowerCase()]||t.replace(/\b\w/g,c=>c.toUpperCase())};
let pausedForCompletion=false;

function backupNow(){const b={id:uid(),createdAt:new Date().toISOString(),schemaVersion:Number(localStorage.getItem('sw2_schema_version')||0),data:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('sw2_')&&k!=='sw2_backups')b.data[k]=localStorage.getItem(k)}const bs=read('sw2_backups',[]);bs.unshift(b);write('sw2_backups',bs.slice(0,10));return b}
function migrate(){if(Number(localStorage.getItem('sw2_schema_version')||0)>=SCHEMA)return;backupNow();const arrays=['sw2_library','sw2_history','sw2_plans','sw2_custom_equipment_names','sw2_custom_equipment_types','sw2_custom_muscles','sw2_profile_history','sw2_offline_queue'];for(const k of arrays)write(k,Array.isArray(read(k,[]))?read(k,[]):[]);write('sw2_history',read('sw2_history',[]).map(w=>({...w,id:w.id||uid(),date:w.date||new Date().toISOString(),updatedAt:w.updatedAt||w.date||new Date().toISOString(),exercises:(w.exercises||[]).map(x=>({...x,id:x.id||uid(),sets:Array.isArray(x.sets)?x.sets:[]}))})));localStorage.setItem('sw2_schema_version',String(SCHEMA))}

function suffixName(name,type){let n=String(name||'').trim().replace(/\s+/g,' ');let want='';if(type==='Mat')want='Mat';else if(type==='Bench')want='Bench';else if(String(type).includes('Machine'))want='Machine';if(!want)return n;if(new RegExp(`\\(${want}\\)$`,'i').test(n))return n.replace(new RegExp(`\\(${want}\\)$`,'i'),`(${want})`);n=n.replace(/\s*\((Mat|Bench|Machine)\)$/i,'');return `${n} (${want})`}
function setupNaming(){const f=el('exerciseForm');if(!f||f.dataset.v2422)return;f.dataset.v2422='1';const inp=el('editEquipmentName');let dl=el('equipmentNameList2422');if(!dl){dl=document.createElement('datalist');dl.id='equipmentNameList2422';document.body.appendChild(dl)}inp?.setAttribute('list',dl.id);const refresh=()=>dl.innerHTML=read('sw2_custom_equipment_names',[]).map(x=>`<option value="${esc(x)}"></option>`).join('');refresh();f.addEventListener('submit',()=>{const type=normalize(el('editEquipmentType')?.value);el('editName').value=suffixName(el('editName').value,type);if(inp){const v=normalize(inp.value);inp.value=v;if(v){const a=read('sw2_custom_equipment_names',[]);if(!a.some(x=>x.toLowerCase()===v.toLowerCase())){a.push(v);write('sw2_custom_equipment_names',a);refresh()}}}},true)}

function stats(items){let sets=0,reps=0,volume=0,cardio=0,floors=0;const muscles=new Set();for(const x of items||[]){if(x.primaryGroup)muscles.add(x.primaryGroup);if(x.secondaryGroup)muscles.add(x.secondaryGroup);if(x.kind==='cardio'){cardio+=Number(x.minutes)||0;floors+=Number(x.floors)||0}else for(const s of x.sets||[]){sets++;reps+=Number(s.reps)||0;volume+=(Number(s.reps)||0)*(Number(s.weight)||0)}}return{sets,reps,volume,cardio,floors,muscles:[...muscles]}}
function latest(ex){for(const w of read('sw2_history',[]).slice().sort((a,b)=>new Date(b.date)-new Date(a.date))){const x=(w.exercises||[]).find(y=>(ex.id&&y.id===ex.id)||y.name?.toLowerCase()===ex.name?.toLowerCase());if(x)return x}return null}
function preload(ex){const x=cp(ex),p=latest(ex);x.done=false;x.effort='';x.note='';if(p){if(x.kind==='cardio'){x.minutes=p.minutes??x.minutes;x.floors=p.floors??x.floors}else x.sets=cp(p.sets||x.sets||[])}return x}
function patchAllRoutes(){window.cleanForToday=items=>(items||[]).map(preload);window.addNamed=id=>{const x=library.find(e=>e.id===id);if(x){exercises.push(preload(x));renderToday();persist();showPage('today')}}}

function completion(){const finish=el('finishBtn'),back=el('completeBackBtn');const open=finish?.onclick;if(finish)finish.onclick=()=>{pausedForCompletion=!!running;open?.();setTimeout(()=>{const s=stats((exercises||[]).filter(x=>x.done)),box=el('completionStats');if(box){box.querySelectorAll('[data-v2422]').forEach(x=>x.remove());box.insertAdjacentHTML('beforeend',`<div class="history-stat" data-v2422><b>${s.cardio}</b><span>Cardio min</span></div><div class="history-stat" data-v2422><b>${s.floors}</b><span>Floors</span></div>`) }},0)};if(back)back.onclick=()=>{showPage('today');if(pausedForCompletion&&!running){running=true;start=Date.now();interval=setInterval(tick,1000);persist();tick()}pausedForCompletion=false}}

function equipmentMatch(x,filter){if(filter==='Any')return true;const t=x.equipmentType||'';const map={Machines:v=>v.includes('Machine'),Cable:v=>v==='Cable Machine',Dumbbells:v=>v==='Dumbbell',Bodyweight:v=>v==='Bodyweight',Mat:v=>v==='Mat',Bench:v=>v==='Bench','Resistance Band':v=>v==='Resistance Band',Barbell:v=>v==='Barbell',Kettlebell:v=>v==='Kettlebell','TRX / Suspension':v=>v==='TRX / Suspension'};return (map[filter]||(()=>true))(t)}
function generateBalanced(){const focus=el('randomFocus').value,diff=el('randomDifficulty').value,dur=+el('randomDuration').value,requested=+el('randomCount').value,eq=el('randomEquipment').value,custom=[...(el('randomMuscles')?.selectedOptions||[])].map(o=>o.value);const maps={'Upper Body':['Chest','Back','Shoulders','Biceps','Triceps'],'Lower Body':['Quads','Hamstrings','Glutes','Hips','Calves'],'Push':['Chest','Shoulders','Triceps','Quads'],'Pull':['Back','Biceps','Hamstrings'],'Legs':['Quads','Hamstrings','Glutes','Hips','Calves'],'Core':['Core'],'Cardio':['Cardio'],'Full Body':MUSCLE_GROUPS};const groups=focus==='Custom'?custom:(maps[focus]||MUSCLE_GROUPS);if(!groups.length)return alert('Select at least one muscle group.');let pool=library.filter(x=>groups.includes(x.primaryGroup)&&equipmentMatch(x,eq));if(!pool.length)return alert('No exercises match those filters.');const timeCap=Math.max(1,Math.floor(dur/(diff==='Beginner'?5:diff==='Advanced'?7:6)));const count=Math.min(requested,timeCap,pool.length);const buckets=groups.map(g=>pool.filter(x=>x.primaryGroup===g)).filter(a=>a.length);const chosen=[],usedMove=new Map();let turn=0,guard=0;while(chosen.length<count&&guard++<1000){const b=buckets[turn++%buckets.length];const options=b.filter(x=>!chosen.some(c=>c.id===x.id)).sort(()=>Math.random()-.5);const pick=options.find(x=>(usedMove.get(x.movement)||0)===0)||options[0];if(pick){chosen.push(preload(pick));usedMove.set(pick.movement,(usedMove.get(pick.movement)||0)+1)}if(!buckets.some(a=>a.some(x=>!chosen.some(c=>c.id===x.id))))break}const setCount=diff==='Beginner'?2:diff==='Advanced'?4:3,repCount=diff==='Beginner'?10:diff==='Advanced'?8:12;const cardioN=chosen.filter(x=>x.kind==='cardio').length;for(const x of chosen){if(x.kind==='cardio'){if(!latest(x))x.minutes=Math.max(5,Math.floor(dur/Math.max(1,cardioN)));continue}if(!latest(x))x.sets=Array.from({length:setCount},()=>({reps:repCount,weight:x.sets?.[0]?.weight||''}))}if(!confirmReplace())return;exercises=chosen;localStorage.setItem('sw2_workout_title',`${dur}-Minute ${diff} ${focus} Workout`);persist();renderToday();renderDashboard();el('randomWorkoutDialog').close();showPage('today')}

function parseSetText(line){const sets=[];for(const m of line.matchAll(/(\d+)\s*[x×]\s*(\d+)\s*@\s*([\d.]+)\s*lb?/gi))sets.push(...Array.from({length:+m[1]},()=>({reps:+m[2],weight:+m[3]})));if(!sets.length)for(const m of line.matchAll(/(?:^|,\s*)(\d+)\s*@\s*([\d.]+)\s*lb?/gi))sets.push({reps:+m[1],weight:+m[2]});if(!sets.length){const m=line.match(/(\d+)\s*[x×]\s*(\d+)(?!\s*@)/i);if(m)sets.push(...Array.from({length:+m[1]},()=>({reps:+m[2],weight:''})))}return sets}
function parseWorkout(text){const result={title:'Pasted Workout',notes:'',items:[]};let cur=null;for(const raw of text.split(/\r?\n/)){let line=raw.trim();if(!line)continue;let m=line.match(/^Workout(?: Title)?:\s*(.+)$/i);if(m){result.title=m[1];continue}m=line.match(/^Workout Notes?:\s*(.+)$/i);if(m){result.notes=m[1];continue}if(/^Effort:/i.test(line)&&cur){cur.effort=line.replace(/^Effort:\s*/i,'');continue}if(/^Note:/i.test(line)&&cur){cur.note=line.replace(/^Note:\s*/i,'');continue}line=line.replace(/^✔\s*/,'');const name=(line.split(':')[0]||line).trim();const found=library.slice().sort((a,b)=>b.name.length-a.name.length).find(x=>line.toLowerCase().includes(x.name.toLowerCase()));cur=found?preload(found):{id:uid(),name,primaryGroup:'',primaryType:'',secondaryGroup:'',secondaryType:'',movement:'',equipmentName:'',equipmentType:'',kind:/\bmin\b/i.test(line)?'cardio':'strength',sets:[]};cur._missing=!found;const cm=line.match(/(\d+)\s*min(?:utes?)?(?:,?\s*(\d+)\s*floors?)?/i);if(cm){cur.kind='cardio';cur.minutes=+cm[1];cur.floors=cm[2]?+cm[2]:'';cur.sets=[]}else{const s=parseSetText(line);if(s.length)cur.sets=s}result.items.push(cur)}return result}
function ensurePasteDialog(){if(el('pasteReview2422'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="pasteReview2422"><div class="modal"><h2>Review Pasted Workout</h2><div id="pasteMeta2422"></div><div id="pasteItems2422"></div><div class="actions"><button class="btn ghost" onclick="pasteReview2422.close()">Cancel</button><button class="btn primary" id="confirmPaste2422">Load Workout</button></div></div></dialog>`)}
let pasteDraft=null;
function reviewPaste(){pasteDraft=parseWorkout(el('pasteWorkoutText').value);if(!pasteDraft.items.length)return alert('No exercises were recognized.');ensurePasteDialog();el('pasteMeta2422').innerHTML=`<div class="field"><label>Workout Title</label><input id="pasteTitle2422" value="${esc(pasteDraft.title)}"></div><div class="field"><label>Workout Notes</label><textarea id="pasteNotes2422">${esc(pasteDraft.notes)}</textarea></div>`;el('pasteItems2422').innerHTML=pasteDraft.items.map((x,i)=>`<div class="card" data-pi="${i}"><div class="field"><label>Exercise</label><input data-k="name" value="${esc(x.name)}"></div>${x._missing?`<div class="small danger">Not in Exercise Library. Complete the fields below to save it.</div><div class="grid2">${[['primaryGroup','Primary Group'],['primaryType','Primary Type'],['secondaryGroup','Secondary Group'],['secondaryType','Secondary Type'],['movement','Movement Pattern'],['equipmentName','Equipment Name'],['equipmentType','Equipment Type']].map(([k,l])=>`<div class="field"><label>${l}</label><input data-k="${k}" value="${esc(x[k]||'')}"></div>`).join('')}</div>`:''}<div class="field"><label>Effort</label><input data-k="effort" value="${esc(x.effort||'')}"></div><div class="field"><label>Exercise Note</label><input data-k="note" value="${esc(x.note||'')}"></div></div>`).join('');el('pasteItems2422').querySelectorAll('[data-k]').forEach(i=>i.oninput=()=>pasteDraft.items[+i.closest('[data-pi]').dataset.pi][i.dataset.k]=i.value);el('pasteReview2422').showModal()}
function loadPaste(){pasteDraft.title=el('pasteTitle2422').value.trim()||'Pasted Workout';pasteDraft.notes=el('pasteNotes2422').value.trim();for(const x of pasteDraft.items.filter(y=>y._missing)){const need=['name','primaryGroup','primaryType','movement','equipmentType'].filter(k=>!x[k]);if(need.length)return alert(`${x.name||'Unnamed exercise'} is missing: ${need.join(', ')}`);x.name=suffixName(x.name,normalize(x.equipmentType));x.equipmentType=normalize(x.equipmentType);x.equipmentName=normalize(x.equipmentName);const saved={...cp(x)};delete saved._missing;if(!library.some(e=>e.name.toLowerCase()===saved.name.toLowerCase()))library.push(saved)}if(!confirmReplace())return;exercises=pasteDraft.items.map(x=>{const y=cp(x);delete y._missing;y.done=false;return y});localStorage.setItem('sw2_workout_title',pasteDraft.title);el('workoutNotes').value=pasteDraft.notes;persist();renderLibrary();renderToday();el('pasteReview2422').close();el('pasteWorkoutDialog').close();showPage('today')}

let importRows=[];
function parseBlocks(text){return text.trim().split(/\n\s*\n/).map(b=>{const o={};for(const l of b.split(/\n/)){const m=l.match(/^([^:]+):\s*(.*)$/);if(m)o[m[1].trim().toLowerCase()]=m[2].trim()}return{name:o.exercise||'',primaryGroup:o['primary group']||'',primaryType:o['primary type']||'',secondaryGroup:/^none$/i.test(o['secondary group']||'')?'':o['secondary group']||'',secondaryType:/^none$/i.test(o['secondary type']||'')?'':o['secondary type']||'',movement:o['movement pattern']||o.movement||'',equipmentName:o['equipment name']||'',equipmentType:o['equipment type']||'',include:true,duplicateChoice:'Skip',newName:''}}).filter(x=>x.name)}
function validateImport(x){const e=[];for(const k of ['name','primaryGroup','primaryType','movement','equipmentType'])if(!x[k])e.push(k);if((x.secondaryGroup&&!x.secondaryType)||(!x.secondaryGroup&&x.secondaryType))e.push('secondary group/type pair');return e}
function showImportReview(){importRows=parseBlocks(el('exerciseImportText').value);const host=el('importReviewList242');host.innerHTML=importRows.map((x,i)=>{const dup=library.some(e=>e.name.toLowerCase()===x.name.toLowerCase());return `<div class="card" data-ii="${i}"><label><input type="checkbox" data-k="include" checked> Include</label><div class="grid2">${[['name','Exercise'],['primaryGroup','Primary Group'],['primaryType','Primary Type'],['secondaryGroup','Secondary Group'],['secondaryType','Secondary Type'],['movement','Movement Pattern'],['equipmentName','Equipment Name'],['equipmentType','Equipment Type']].map(([k,l])=>`<div class="field"><label>${l}</label><input data-k="${k}" value="${esc(x[k])}"></div>`).join('')}</div>${dup?`<div class="field"><label>Duplicate Resolution</label><select data-k="duplicateChoice"><option>Skip</option><option>Update Existing</option><option>Create New (Rename)</option></select></div><div class="field hidden rename2422"><label>New Exercise Name</label><input data-k="newName" value="${esc(x.name+' Copy')}"></div>`:'<div class="small success-text">No duplicate found</div>'}<div class="validation"></div></div>`}).join('')||'<div class="empty">Nothing recognized.</div>';host.querySelectorAll('[data-k]').forEach(n=>{n.oninput=()=>{const row=n.closest('[data-ii]'),x=importRows[+row.dataset.ii];x[n.dataset.k]=n.type==='checkbox'?n.checked:n.value;if(n.dataset.k==='duplicateChoice')row.querySelector('.rename2422')?.classList.toggle('hidden',n.value!=='Create New (Rename)');row.querySelector('.validation').textContent=validateImport(x).join(' · ')}});el('importReviewDialog242').showModal()}
function saveImports(){let saved=0,skipped=0,failed=0;for(const x of importRows){if(!x.include){skipped++;continue}if(validateImport(x).length){failed++;continue}x.equipmentType=normalize(x.equipmentType);x.equipmentName=normalize(x.equipmentName);let name=suffixName(x.name,x.equipmentType);const dup=library.find(e=>e.name.toLowerCase()===x.name.toLowerCase()||e.name.toLowerCase()===name.toLowerCase());if(dup){if(x.duplicateChoice==='Update Existing'){Object.assign(dup,{...x,name});saved++}else if(x.duplicateChoice==='Create New (Rename)'){name=suffixName(x.newName||`${x.name} Copy`,x.equipmentType);library.push({id:uid(),...x,name,...defaults(x.primaryGroup==='Cardio')});saved++}else skipped++}else{library.push({id:uid(),...x,name,...defaults(x.primaryGroup==='Cardio')});saved++}}persist();renderLibrary();el('importReviewDialog242').close();el('exerciseImportDialog').close();alert(`${saved} saved · ${skipped} skipped · ${failed} need attention`);if(failed)showImportReview()}

function insights(id){const ex=library.find(x=>x.id===id);if(!ex)return;const rows=[];for(const w of read('sw2_history',[]).slice().sort((a,b)=>new Date(a.date)-new Date(b.date)))for(const x of w.exercises||[])if(x.id===id||x.name?.toLowerCase()===ex.name.toLowerCase())rows.push({w,x});const totalSets=rows.reduce((n,r)=>n+(r.x.sets?.length||0),0),max=Math.max(0,...rows.flatMap(r=>r.x.sets||[]).map(s=>Number(s.weight)||0)),totalVol=rows.reduce((n,r)=>n+stats([r.x]).volume,0),totalReps=rows.reduce((n,r)=>n+stats([r.x]).reps,0);const first=rows[0],last=rows.at(-1);let trend='Complete more sessions to see trends.';if(rows.length>1){if(ex.kind==='cardio'){const d=(Number(last.x.minutes)||0)-(Number(first.x.minutes)||0),f=(Number(last.x.floors)||0)-(Number(first.x.floors)||0);trend=`Cardio duration ${d>=0?'increased':'decreased'} by ${Math.abs(d)} min; floors ${f>=0?'increased':'decreased'} by ${Math.abs(f)}.`}else{const fm=Math.max(0,...(first.x.sets||[]).map(s=>Number(s.weight)||0)),lm=Math.max(0,...(last.x.sets||[]).map(s=>Number(s.weight)||0));trend=`Max weight ${lm>=fm?'increased':'decreased'} by ${Math.abs(lm-fm)} lb. Total recorded volume: ${Math.round(totalVol).toLocaleString()} lb; reps: ${totalReps}.`}}el('exerciseHistoryTitle242').textContent=`${ex.name} History`;el('exerciseHistoryBody242').innerHTML=`<div class="history-insights"><div class="history-stat"><b>${rows.length}</b><span>Sessions</span></div><div class="history-stat"><b>${last?new Date(last.w.date).toLocaleDateString():'—'}</b><span>Last Performed</span></div><div class="history-stat"><b>${totalSets}</b><span>Total Sets</span></div><div class="history-stat"><b>${max}</b><span>Max Weight</span></div></div><div class="card"><b>Progress Insights</b><p>${esc(trend)}</p></div>${rows.slice().reverse().map(r=>`<div class="card"><b>${new Date(r.w.date).toLocaleDateString()}</b><div>${esc(exerciseCurrent(r.x))}</div>${r.x.effort?`<div>Effort: ${esc(r.x.effort)}</div>`:''}${r.x.note?`<div>Note: ${esc(r.x.note)}</div>`:''}</div>`).join('')||'<div class="empty">No completed sessions yet.</div>'}`;el('exerciseHistoryDialog242').showModal()}

function structuredHistory(){const old=window.renderHistory;if(typeof old!=='function'||old.__v2422)return;const wrap=function(){old();const hist=read('sw2_history',[]);for(const w of hist){const id=String(w.id||'').replace(/[^\w-]/g,''),box=el(`hist-${id}`);if(!box)continue;const s=stats(w.exercises);const detail=`<div class="history-summary-grid"><div><b>${Math.round((w.duration||0)/60000)}</b><span>Minutes</span></div><div><b>${(w.exercises||[]).length}</b><span>Exercises</span></div><div><b>${s.sets}</b><span>Sets</span></div><div><b>${s.reps}</b><span>Reps</span></div><div><b>${Math.round(s.volume)}</b><span>Volume</span></div><div><b>${s.cardio}</b><span>Cardio min</span></div><div><b>${s.floors}</b><span>Floors</span></div></div>${w.notes?`<div class="note-block"><b>Workout Notes</b><p>${esc(w.notes)}</p></div>`:''}${(w.exercises||[]).map(x=>`<section class="history-exercise"><h4>${esc(x.name)}</h4>${x.kind==='cardio'?`<div>Minutes: ${x.minutes||0} · Floors: ${x.floors||0}</div>`:`<table class="history-set-table"><thead><tr><th>Set</th><th>Reps</th><th>Weight</th></tr></thead><tbody>${(x.sets||[]).map((s,i)=>`<tr><td>${i+1}</td><td>${s.reps||0}</td><td>${s.weight||0}</td></tr>`).join('')}</tbody></table>`}${x.effort?`<p><b>Effort:</b> ${esc(x.effort)}</p>`:''}${x.note?`<p><b>Exercise Note:</b> ${esc(x.note)}</p>`:''}</section>`).join('')}`;const summary=box.querySelector('.summary-line');if(summary)summary.outerHTML=detail}};wrap.__v2422=true;window.renderHistory=wrap;wrap()}

function dashboard(){const d=el('dashboard');if(!d)return;const hero=d.querySelector('.hero'),streak=d.querySelector('.streak')?.closest('.card'),today=el('todayWorkoutCard'),last=el('lastWorkoutCard'),quickTitle=d.querySelector('.quick-title'),quick=d.querySelector('.quick'),metrics=d.querySelector('.metrics'),tip=d.querySelector('.tip'),help=el('dashboardHelp2421');[hero,streak,today,last,quickTitle,quick,metrics,tip,help].filter(Boolean).forEach(n=>d.appendChild(n));metrics?.classList.add('compact-metrics');const old=window.renderDashboard;if(typeof old==='function'&&!old.__v2422){const wrap=function(){old();setTimeout(()=>{const w=read('sw2_history',[]).sort((a,b)=>new Date(b.date)-new Date(a.date))[0],card=el('lastWorkoutCard');if(w&&card){const b=[...card.querySelectorAll('button')].find(x=>/view summary/i.test(x.textContent));if(b)b.onclick=()=>{showPage('history');setTimeout(()=>{const id=String(w.id).replace(/[^\w-]/g,'');const detail=el(`hist-${id}`);detail?.classList.remove('hidden');detail?.scrollIntoView({block:'start'})},0)}}},0)};wrap.__v2422=true;window.renderDashboard=wrap;wrap()}}

const cloudKeys=['sw2_library','sw2_today','sw2_plans','sw2_history','sw2_notes','sw2_custom_equipment_names','sw2_custom_equipment_types','sw2_custom_muscles','sw2_schema_version','sw2_profile','sw2_profile_name','sw2_profile_history','sw2_running','sw2_start','sw2_elapsed','sw2_sync_state','sw2_workout_title'];
function snapshot(){const out={updatedAt:new Date().toISOString(),schemaVersion:SCHEMA};for(const k of cloudKeys){const v=localStorage.getItem(k);if(v!==null)out[k]=v}return out}
function applySnapshot(r){for(const k of cloudKeys)if(Object.hasOwn(r,k))localStorage.setItem(k,r[k]);write('sw2_sync_state',{updatedAt:r.updatedAt||new Date().toISOString(),status:'connected'})}
function queueUpload(s=snapshot()){const q=read('sw2_offline_queue',[]);q.push({id:uid(),op:'upload',createdAt:new Date().toISOString(),snapshot:s});write('sw2_offline_queue',q);queueStatus()}
function queueStatus(){const q=read('sw2_offline_queue',[]),s=el('cloudStatus2421');if(s&&q.length)s.textContent=`${q.length} offline upload${q.length===1?'':'s'} queued`}
async function ref(){if(!window.firebase?.auth()?.currentUser)throw new Error('Sign in to use cloud sync.');return firebase.firestore().collection('users').doc(firebase.auth().currentUser.uid).collection('app').doc('state')}
async function upload(){const s=snapshot();try{await (await ref()).set(s,{merge:false});write('sw2_offline_queue',[]);write('sw2_sync_state',{updatedAt:s.updatedAt,status:'connected'});queueStatus();alert('Local data uploaded.')}catch(e){queueUpload(s);alert(`Upload queued: ${e.message}`)}}
async function download(){try{const doc=await (await ref()).get();if(!doc.exists)return alert('No cloud data is available.');const remote=doc.data(),local=snapshot();let c='REMOTE';if(localStorage.getItem('sw2_sync_state'))c=(prompt('Cloud and local data differ. Type REMOTE, LOCAL, or CANCEL.','REMOTE')||'CANCEL').trim().toUpperCase();if(c==='CANCEL')return;if(c==='LOCAL')return upload();if(c!=='REMOTE')return alert('Choose REMOTE, LOCAL, or CANCEL.');applySnapshot(remote);location.reload()}catch(e){alert(e.message)}}
async function flush(){const q=read('sw2_offline_queue',[]);if(!q.length)return;try{const r=await ref();for(const x of q)await r.set(x.snapshot,{merge:false});write('sw2_offline_queue',[]);queueStatus()}catch(e){console.warn(e)}}
function dataPanels(){const settings=el('settings');if(settings&&!el('backupPanel2422'))settings.insertAdjacentHTML('beforeend',`<div class="card" id="backupPanel2422"><h3>Data Backups</h3><div id="backupList2422"></div><button class="btn secondary" id="createBackup2422">Create Backup Now</button></div>`);const render=()=>{const h=el('backupList2422');if(!h)return;h.innerHTML=read('sw2_backups',[]).map((b,i)=>`<div class="backup-row"><span>${new Date(b.createdAt).toLocaleString()} · schema ${b.schemaVersion}</span><button class="btn ghost" data-r="${i}">Restore</button></div>`).join('')||'<p class="small muted">No backups yet.</p>';h.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{const x=read('sw2_backups',[])[+b.dataset.r];if(!x||!confirm('Restore this backup?'))return;for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k?.startsWith('sw2_')&&k!=='sw2_backups')localStorage.removeItem(k)}for(const [k,v] of Object.entries(x.data))localStorage.setItem(k,v);location.reload()})};el('createBackup2422')&&(el('createBackup2422').onclick=()=>{backupNow();render()});render();const p=el('cloudPanel2421');if(p&&!el('uploadCloud2422')){p.insertAdjacentHTML('beforeend',`<div class="actions"><button class="btn secondary" id="uploadCloud2422">Upload</button><button class="btn secondary" id="downloadCloud2422">Download</button><button class="btn ghost" id="viewQueue2422">View Queue</button></div>`);el('uploadCloud2422').onclick=upload;el('downloadCloud2422').onclick=download;el('viewQueue2422').onclick=()=>{const q=read('sw2_offline_queue',[]);alert(q.length?q.map(x=>`${new Date(x.createdAt).toLocaleString()} · ${x.op}`).join('\n'):'The offline queue is empty.')};window.addEventListener('online',flush);queueStatus()}}

function wire(){for(const v of ['Mat','Bench','Resistance Band','Barbell','Kettlebell','TRX / Suspension'])if(![...el('randomEquipment').options].some(o=>o.value===v))el('randomEquipment').add(new Option(v,v));el('generateRandomBtn').onclick=generateBalanced;el('loadPastedWorkoutBtn').onclick=reviewPaste;ensurePasteDialog();el('confirmPaste2422').onclick=loadPaste;el('previewExerciseImportBtn').onclick=showImportReview;el('saveExerciseImportBtn').onclick=showImportReview;el('saveImport242').onclick=saveImports;window.openExerciseInsights=insights}
function version(){document.title=`Sweat & Stats v${VERSION}`;document.querySelectorAll('*').forEach(n=>{if(!n.children.length&&/^v2\.4\.0\.2(?:\.1)?$/.test(n.textContent.trim()))n.textContent=`v${VERSION}`})}
function init(){migrate();setupNaming();patchAllRoutes();completion();wire();structuredHistory();dashboard();dataPanels();version();setTimeout(()=>{structuredHistory();dashboard();dataPanels()},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
